### ISSUE TITLE
📛 Uploading process stops after some time

### ISSUE THREAD

**Issue by antonyharfield** [rfcx/ingest-app#137]
## Background

When the user queues a lot of files to upload, sometimes the files just got stuck in the queue, the number or status of files just been the same for so long like nothing is happening

## Technical issue
There seems to be a problem with an upload renderer process, that sometimes it stoped while other renderers and the main process are still running fine

## Expected Outcome
- The main process should know when the uploading process stopped
- The user should be able to get the process up and running again without closing the app

## Actions
- [x] Main process should catch when the renderer has stopped
- [x] Error message dialog with a retry button for the user to get the process to run again

## Exclude
- [ ] A way to track performance of the app (#141)

**Comment by naluinui** [comment]
https://www.electronjs.org/docs/latest/api/web-contents#event-render-process-gone
