### ISSUE TITLE
📛 Detect when AudioMoth files are in local time

### ISSUE THREAD

**Issue by antonyharfield** [rfcx/ingest-app#139]
## Background
- The user often skips to select a timezone of the uploading files, and sometimes that created a huge mess due to the files being uploaded in the wrong timezone which will need a manual work from our side to update the timezone afterward
- Files recorded with AudioMoth always come with timezone in metadata. So there should be a way for the Uploader app to be smarter to figure out the timezone of the files without forcing the user to choose one all the time.

## Expected Outcome
Uploader app should detect when AudioMoth files are in local time, and only warn you if you change from the default detected to something else (e.g. change from local to UTC or vice-versa).

- [ ] #154
- [ ] ~~When changing filename timezone, the “Recorded time (Local)” in the file list should be updated (part of #154)~~
- [x] Remove “File Header” option from Filename Format
- [x] Filename timezone should have Audiomoth config option and it should be default selected when you upload the Audiomoth files (Disabled Audiomoth options if it’s not AudioMoth Files)
- [x] Support 2 types of AudioMoth files (with/without timezone)
- [ ] (bonus) Timezone in filename

**Comment by naluinui** [comment]
- Rename timestamp column to “Recorded time (Local)”
- When changing filename timezone, the “Recorded time (Local)” in the file list should be updated
- Remove “File Header” option from Filename Format
- Filename timezone should have Audiomoth config option and it should be default selected when you upload the Audiomoth files
- Support 2 types of AudioMoth files (with/without timezone)
- Disabled Audiomoth options if it’s not AudioMoth Files
- (bonus) Timezone in filename

**Comment by naluinui** [comment]
https://www.loom.com/share/011d5e26d23b4cb7898f1573cd6e1d8e
