### ISSUE TITLE
App shouldn't auto retry to upload files when the server is down

### ISSUE THREAD

**Issue by naluinui** [rfcx/ingest-app#157]
### Background
In the app, we have the functionality to retry uploading the files 3 times before throwing an error to the user. But most of the time the error was that the server is down, temporarily stopped.

### Tasks
- [ ] App shouldn't auto retry to upload files when the server is down

**Comment by koonchaya** [comment]
The number of uploaded files went down (see screen recordings)
Site : GU47

https://user-images.githubusercontent.com/87486094/170204307-b72b2f57-c799-40e0-8de6-5a29974c62ed.mp4



https://user-images.githubusercontent.com/87486094/170204319-9886f2b8-1eca-492b-890b-bbc00ab40a24.mp4

**Comment by koonchaya** [comment]
Check on this ticket instead : https://github.com/rfcx/engineering-support/issues/7
