### ISSUE TITLE
Uploading process stop after about 3 hours

### ISSUE THREAD

**Issue by koonchaya** [rfcx/ingest-app#159]
**Describe the bug**
App stopped uploading after about 3 hours since the beginning. I had to quit the app and reopen app to continue uploading.

**To Reproduce**
1.Upload >10k files
2.Start upload

**Expected behavior**
App continue uploads files until finish.

**Screenshots**
[May 25 2022.zip](https://github.com/rfcx/ingest-app/files/8771780/May.25.2022.zip)

<img width="730" alt="Screen Shot 2565-05-25 at 20 58 47" src="https://user-images.githubusercontent.com/87486094/170280224-2430508c-739c-4ccf-bc76-638fbcf9456c.png">

**Context**
- Version: 1.4.10

**Comment by naluinui** [comment]
Related to #145
