### ISSUE TITLE
Add Site map - "?" icon in the bottom right-hand corner obscurs the zoom out icon

### ISSUE THREAD

**Issue by koonchaya** [rfcx/ingest-app#163]
**Describe the bug**
Add Site map - "?" icon in the bottom right-hand corner obscurs the zoom out icon
<img width="626" alt="Screen Shot 2565-07-25 at 13 59 44" src="https://user-images.githubusercontent.com/87486094/180717029-9bc3cd96-7a0c-4300-b769-c0ea969f2cc0.png">

**Comment by naluinui** [comment]
https://github.com/rfcx/engineering-support/issues/94
