### ISSUE TITLE
Uploader - don't show site not created to legacy on the Uploader

### ISSUE THREAD

**Issue by koonchaya** [rfcx/ingest-app#211]
I just found a new case that when the site is not created successfully. It shows on the Uploader app. For example, I created a site from Uploader app and I got the error "Failed creating stream source file and segments". I cannot see this site in Arbimon but I can see this site on the list when I select a project from the Uploader app. From the screenshot shows 2 sites (zero location and zero location2) that don't exist in the project on site page. I think this case we should not show this kind of site on Uploader.

![Image](https://github.com/rfcx/arbimon-uploader/assets/87486094/ce6742de-4710-4864-92dc-d447e88e9039)

**Comment by naluinui** [comment]
This looks like the site is existing in Core, but not Arbimon. Maybe we can ask Frongs or someone in the Core team to do something on Ingest service to prevent this case? -- don't returning the site name to the list of arbimon_id is null

**Comment by koonchaya** [comment]
This is fixed on the version 1.5.7
