### ISSUE TITLE
Arbimon uploader - upload audio files with the large issue (1-min files every 3 minutes)

### ISSUE THREAD

**Issue by RatreeOchn** [rfcx/ingest-app#216]
Original post: https://rfcx.slack.com/archives/C01BW5M71JS/p1711477643671119
From: Carly

> New user support request, you’re cc’d on the email. I’ve asked her to send us one of the large files so that we can test it to trouble-shoot. thanks!
> https://arbimon.org/p/tai-gunshots

![Image](https://github.com/rfcx/arbimon-uploader/assets/51106210/d736ac14-e415-4bc1-afdd-1b8d9a88f463)

**Comment by rassokhina-e** [comment]
I found a problem, the arbimon-ingest-consumer log shows us the core sent to arbimon each first file in each 3 minutes, but the core segments have all 60 files for this 1 hour recording from the user example. So we can restore missed 40 files to the arbimon db. I can help with this. Another work, to find an original problem and we have to create a ticket on the core side with this description.

**arbimon-ingest-consumer log**



![Image](https://github.com/rfcx/arbimon-uploader/assets/31901584/d5fcf281-8ec4-4619-92e1-e729a2399e72)




**core saves all 60 files to the core db**



![Image](https://github.com/rfcx/arbimon-uploader/assets/31901584/4a6d3d28-2204-42a8-8941-2956b5014d4f)

**Comment by rassokhina-e** [comment]
I created core task https://github.com/rfcx/rfcx-api/issues/580

**Comment by rassokhina-e** [comment]
Recovered recording from the user's request
site: 51613 `Tai C11F`
date: 29 November 2023

**Comment by koonchaya** [comment]
I checked the files are correct. I can see every 1-min recordings.

**Comment by koonchaya** [comment]
I tested uploading 1 hour file to my project. I don't see the issue. All 60 files showed up in my project. 
Project: https://arbimon.org/project/the-green-place-phitsanulok/audiodata/recordings
Site: 29 Mar 2024
