### ISSUE TITLE
Uploader error message "Cannot create source file with provided data"

### ISSUE THREAD

**Issue by koonchaya** [rfcx/ingest-app#217]
Original post: https://rfcx.slack.com/archives/C03FD1WD02J/p1712661570627809
From: Layla

I also found this error message from uploading some of the files but these files are available in the project. I can open the file in visualizer. We should find out why it is showing this error message.

![Image](https://github.com/rfcx/arbimon-uploader/assets/87486094/55151bee-01f1-4301-9bdd-114efcb50d16)

## Additional detail
Frongs investigated and found that this error came from the Uploader app uploads 1 file 6 times in 2 seconds. 

Example of uploaded file from this error
https://arbimon.org/project/puerto-rico-island-wide/visualizer/rec/167078968
https://arbimon.org/project/puerto-rico-island-wide/visualizer/rec/167079877

![Image](https://github.com/rfcx/arbimon-uploader/assets/87486094/ca7c7f12-7373-489d-943c-9d860c73a839)

![Image](https://github.com/rfcx/arbimon-uploader/assets/87486094/de756212-c193-4faf-b4c7-65f0daec2e4a)

## Expected result
- [ ] User should not see this error if the file uploaded successfully

**Comment by rassokhina-e** [comment]
<img width="745" alt="Untitled" src="https://github.com/rfcx/arbimon-uploader/assets/31901584/9f3f52ef-5037-49f0-9de9-0cf2287cdeda">
 Regarding this issue, we are investigating with Frongs, the user sent 1 time recording and got ingested status, but ingest service processed these file twice, in the second time Core sent the duplicate file error

**Comment by rassokhina-e** [comment]
the core side processes duplicate problem for this case, the ingest API gets only once the user request to upload, the ingest API tasks send twice the request, so issue on both side core - cannot process duplicate file and ingest service tasks - sends twice the request

![Image](https://github.com/rfcx/arbimon-uploader/assets/31901584/f75a53ae-3bc7-4067-8b99-6debad6ec2dd)
![Image](https://github.com/rfcx/arbimon-uploader/assets/31901584/e4442058-8bbb-4836-8644-a6002527e29c)
![Image](https://github.com/rfcx/arbimon-uploader/assets/31901584/b8f3ff66-0554-4107-b341-4b9a54a95965)

**Comment by koonchaya** [comment]
@rassokhina-e What will be the next step?

**Comment by rassokhina-e** [comment]
I found a problem, when the user uploads short files, the process is too quick and when the file is changed the status from waiting to uploading, the system put the same file 1-2 seconds before to the uploading queue again and process it again.

so we just need to change the status of the uploading file straightaway after putting this file in the queue




![Image](https://github.com/rfcx/arbimon-uploader/assets/31901584/5f47c106-8063-4aaf-9dd7-ab6435d0dfc7)
![Image](https://github.com/rfcx/arbimon-uploader/assets/31901584/0700cabb-9fb5-40eb-8bf0-350e240cfe85)

**Comment by koonchaya** [comment]
@rassokhina-e Is the short file including 1-min file? Why is it happening now not before?

**Comment by rassokhina-e** [comment]
this is waiting for the prod release of Uploader, we are going to make in in the nearest week

**Comment by koonchaya** [comment]
@rassokhina-e I got this error with some of the files on mac version.

![Image](https://github.com/rfcx/arbimon-uploader/assets/87486094/3f992c0b-72b3-4fff-87fd-c171d802686c)


![Image](https://github.com/rfcx/arbimon-uploader/assets/87486094/93785e82-fbb6-429d-863d-2adc0ea64bdb)

**Comment by koonchaya** [comment]
Fixed in version 1.5.9

**Comment by rassokhina-e** [comment]
I added the Validation Error description to the error text, so the user can understand the problem better if the error occurs

@koonchaya I'll share with you 1.5.10 directly to check this case

I tested 215 recordings today and found only 1 issue with this text above, the case was related to Validation error from Ingest service

**Comment by koonchaya** [comment]
I don't see the error message so far (tested in several sites and ~200 files per site)

**Comment by grindarius** [comment]
Released in [v1.2.2](https://github.com/rfcx/arbimon/releases/tag/v1.2.2) 🚀
