### ISSUE TITLE
Uploader - make location required to create a new site, but also allow user to upload to hidden sites

### ISSUE THREAD

**Issue by koonchaya** [rfcx/ingest-app#218]
## Background
User will not allow to create a new site without location from the Uploader app. The last quick fix we did was allowing user to create a new site without location and make this site hidden. The next iteration, user can hide the site from Insights from Arbimon edit site pop up and we will still allow user to upload files to the hidden site.

## Expected results
- [x] User cannot create a new site from Uploader without location including 0,0 location
- [x] User can click next button and see the message "[TBD - _The location is required_]" when creating site without location
- [x] User can create a new site from Uploader with location
- [x] User can see site pin on site page map when site created with location
- [x] User can see site pin on overview when site created with location
- [x] User can see the site with location created on Arbimon site page

## Additional requirements
- [x] User can upload files to hidden site (excluded site from Arbimon)

**Comment by koonchaya** [comment]
@tiffanylee0125 Can you suggest the error message [TBD] from above?

**Comment by rassokhina-e** [comment]
>User can upload files to hidden site (excluded site from Arbimon)

case1: Normal site with coordinates

![Image](https://github.com/rfcx/arbimon-uploader/assets/31901584/94feb331-23c4-4691-80dd-ebfdc7849355)
![Image](https://github.com/rfcx/arbimon-uploader/assets/31901584/ae3c292f-7a7c-426a-9ef8-57a43792205d)

**Comment by rassokhina-e** [comment]
![Image](https://github.com/rfcx/arbimon-uploader/assets/31901584/3b252e32-4429-4d26-afa3-05ea7e1f555e)

**Comment by rassokhina-e** [comment]
![Image](https://github.com/rfcx/arbimon-uploader/assets/31901584/166ef26c-f25c-4585-a1da-dbd4f7b7d645)

**Comment by rassokhina-e** [comment]
![Image](https://github.com/rfcx/arbimon-uploader/assets/31901584/67dca617-d55a-406a-a123-b9d59974bb38)
![Image](https://github.com/rfcx/arbimon-uploader/assets/31901584/af3d79cf-14f0-497a-b1c6-15158466fc77)

**Comment by koonchaya** [comment]
@rassokhina-e The site of 0,0 location can be created but the site should be hidden that means the site should  have the hidden icon and exclude from the insights (tick in the checkbox "Exclude...").

Like this 

![Image](https://github.com/rfcx/arbimon-uploader/assets/87486094/4a5832c6-8c1c-4376-bb1e-dacbe64cc3e3)

**Comment by koonchaya** [comment]
![Image](https://github.com/rfcx/arbimon-uploader/assets/87486094/d97a071e-5271-476d-8f68-592db4a6a7f3)
![Image](https://github.com/rfcx/arbimon-uploader/assets/87486094/32ea2ea7-5401-48ec-8c7b-cead5b74371f)

**Comment by grindarius** [comment]
Released in [v1.2.2](https://github.com/rfcx/arbimon/releases/tag/v1.2.2) 🚀
