### ISSUE TITLE
Uploader - fix window auto update

### ISSUE THREAD

**Issue by koonchaya** [rfcx/ingest-app#221]
## Context
When update the window version, I see this error. I cannot use the app after update and I had to uninstall and install the app again to make it works. 

![Image](https://github.com/rfcx/arbimon-uploader/assets/87486094/0b91ec37-da34-4abc-a23c-f5652fd7f13a)

![Image](https://github.com/rfcx/arbimon-uploader/assets/87486094/6be3869c-eafe-4e25-aca6-1e170aaebee0)

## Expected results
- [ ] Can update to the latest version from the popup

**Comment by grindarius** [comment]
Released in [v1.2.2](https://github.com/rfcx/arbimon/releases/tag/v1.2.2) 🚀
