### ISSUE TITLE
Uploader - don't include file in 1970 for the upload and other information

### ISSUE THREAD

**Issue by koonchaya** [rfcx/ingest-app#223]
## Context
We found the timestamps issue from the [partner project ](https://arbimon.org/project/tnc-rfcx-biodiversity-in-parque-nacional-braulio-carrillo-and-la-selva-oet/audiodata/sites). After investigation we found that in the AudioMoth folders containing filename 1970mmdd_hhmmss is causing the issue. When upload with this file, the uploader doesn't upload with the file configuration (UTC-6) but it uploaded with UTC instead. 
See more discussion in https://rfcx.slack.com/archives/C03FD1WD02J/p1715761582406039

It is possible this cause the issue of deployment not found as well. We should not include 1970 file inside the AudioMoth folder to use any information from it.

## Expect results
- [ ] Uploader doesn't include the weird filename (like in 1970) to use for the timezone and deployment
- [ ] When user uploads the AudioMoth files containing 1970 file in site, files should be uploaded with the correct timezone (same as device configuration)
- [ ] When user uploads the AudioMoth files containing 1970 file in site, Uploader should detect the deployment information

**Comment by antonyharfield** [comment]
I think the problem is here: https://github.com/rfcx/arbimon-uploader/blob/4517aedcc6c88e2ce43d2aa992b168d2bc7caa5f/src/renderer/services/file.js#L537

![Screenshot 2567-05-20 at 09 16 34](https://github.com/rfcx/arbimon-uploader/assets/1175362/d453c0a1-10ba-48b4-ac19-a252d12fdd1d)

**Comment by rassokhina-e** [comment]
my test cases:

1.


![Image](https://github.com/rfcx/arbimon-uploader/assets/31901584/187e8a09-4649-4153-a739-5fb5f0c7c45e)



2.



![Image](https://github.com/rfcx/arbimon-uploader/assets/31901584/fbc7a045-d1c0-4e64-a0fd-18261e383f31)



![Image](https://github.com/rfcx/arbimon-uploader/assets/31901584/eda1da45-6dc8-4e54-9e10-d88fd557e72a)

**Comment by rassokhina-e** [comment]
I guess I need the original folder to fix this problem OR if you have the folder with these recs please share it with me @koonchaya

**Comment by grindarius** [comment]
Released in [v1.2.2](https://github.com/rfcx/arbimon/releases/tag/v1.2.2) 🚀

**Comment by koonchaya** [comment]
![Image](https://github.com/rfcx/arbimon-uploader/assets/87486094/6257c42a-e8fe-45b7-99e1-795535d4308d)
