### ISSUE TITLE
User get error "Failed creating stream source file and segments" on Uploader

### ISSUE THREAD

**Issue by koonchaya** [rfcx/ingest-app#224]
Original report https://rfcx.slack.com/archives/C03FD1WD02J/p1717437325255689

>While uploading the second round of deployment, Partners have been  getting the error "Failed creating stream source file and segments".
This is the project link:
https://arbimon.org/project/cameroon-ashej-songmeter-micro/audiodata/recordings
>They used the companion app, deployed the second round and they created new sites after getting the data back from deployment

Site name: Yingui2
User used window version 1.5.5

**Comment by koonchaya** [comment]
## Additional information
I was trying to investigate this issue but I could not open the legacy page of this project. I used support@rfcx.org and the role is project owner.

![Image](https://github.com/rfcx/arbimon-uploader/assets/87486094/944df002-674f-4b92-a4ee-48a5a852015e) 

https://github.com/rfcx/arbimon-uploader/assets/87486094/2b7bbc2d-0cde-4504-84c1-9da509993780

**Comment by rassokhina-e** [comment]
I guess the user renamed the site to Yingui 1, there was a server down problem 01 of June, I see the issue in the logs:
`httpErrorHandler Error: Unable to create recordings in Arbimon`
We can recommend the user to clear the data with top menu and retry the upload

**Comment by rassokhina-e** [comment]
the user did the upload to a new site. We are waiting for the logs and screen from the user to figure out the original issue with the site `Yingui2`

**Comment by koonchaya** [comment]
Solution that we will not allow user to create a new site during the server is down. Created a new ticket https://github.com/rfcx/engineering-support/issues/527#issuecomment-2154194434.
