### ISSUE TITLE
Uploader - error uploading very short file

### ISSUE THREAD

**Issue by koonchaya** [rfcx/ingest-app#225]
Original report: https://rfcx.slack.com/archives/C03FD1WD02J/p1718123083670039

>I was just trying to upload an audio file via the arbimon uploader and its come up with an error 'Validation errors: Parameter 'sample_count' should be an integer'. It is a 30minute clip from a longer .wav file that I cropped in R.
>I (Carly) also tried to upload the file myself and got the same error

Example file https://rfcx.slack.com/archives/C03FD1WD02J/p1718123145781889?thread_ts=1718123083.670039&cid=C03FD1WD02J

![Image](https://github.com/rfcx/arbimon-uploader/assets/87486094/6210364e-0e93-4f4c-a01a-3836e63a65ea)

Fix in https://github.com/rfcx/ingest-service/issues/81

**Comment by Tooseriuz** [comment]
it as expected that the last files is 0.000031 second and null sample count
it can split into 31 files same as ingest service
![Screenshot 2567-06-13 at 17 18 40](https://github.com/rfcx/arbimon-uploader/assets/44440424/9baaf716-5b30-42ce-91e6-8351f17d1696)

from 
```
ffprobe -i out030.wav -show_entries stream=sample_count -show_entries format=duration -v quiet -of csv="p=0"
```

the result is 
```

0.000031
```

the first line should be `sample_count` but it is empty so it means `null`

**Comment by carlybatist** [comment]
@koonchaya is this closed since this ticket is completed - https://github.com/rfcx/ingest-service/issues/81

**Comment by koonchaya** [comment]
This fix hasn't been deployed to production yet.
