### ISSUE TITLE
Uploader - edit filename timezone and add FL tag

### ISSUE THREAD

**Issue by koonchaya** [rfcx/ingest-app#226]
> From our meeting today - 
> cc @koonchaya 

- [x] Add 'FL' tag - like AM 

 
 ![Image](https://github.com/rfcx/arbimon/assets/87486094/1a07436c-f025-4c49-8a57-ce4e19dc56ac)

- [x] Add info icon next to (what will be) Timezone Source → text - “Learn more [here](https://help.arbimon.org/article/179-using-the-arbimon-uploader-app).”
- [x] Rename Filename Timezone → Timezone source 
- [x] Rename the 4 options 
  - [x] a. Device configuration → Timezone in metadata 
  - [x] b. Timezone in filename (keep as is)
  - [x] c. UTC → Ignore file, use UTC
  - [x] d. Site timezone → Ignore file, use site timezone
  - [x] IF songmeter or audiomoth files detected, default should be ‘a’. All other options grayed out/not available to select 
  - [x] IF frontier lab BAR files detected, default should be ‘b’. All other options grayed out/not available to select 
  - [x] IF NOT audiomoth, songmeter or BAR files, default should be option ‘d’ (ignore file, use site timezone) 
 
- [x] Nice to have - option ‘d’ includes site timezone in UTC+5 
- [ ] Grey out options ‘a’ and ‘b’
 
 ![Image](https://github.com/rfcx/arbimon/assets/46716228/6c8c46c3-5f48-4aee-adb7-c44af05e745a)

 _Originally posted by @carlybatist in [#2006](https://github.com/rfcx/arbimon/issues/2006#issuecomment-2147554055)_

**Comment by koonchaya** [comment]
Example frontier lab filename: 20231119T000000+0930_REC_-13.64526+134.30475.wav

**Comment by rassokhina-e** [comment]
![Image](https://github.com/rfcx/arbimon-uploader/assets/31901584/96c14e07-938e-412a-ac59-d7668b12975e)

the link opens a new window



![Image](https://github.com/rfcx/arbimon-uploader/assets/31901584/928aa49e-d88a-4551-9a0d-571d24a58097)
