### ISSUE TITLE
Fix timestamps for PR project

### ISSUE THREAD

**Issue by koonchaya** [rfcx/ingest-app#229]
## Context
According to this issue https://github.com/rfcx/arbimon-uploader/issues/228 and reported from user https://rfcx.slack.com/archives/C03FD1WD02J/p1719236645555979 that the Uploader uploaded the AM files with UTC configuration wrong (uploaded with the site timezone), we will have to fix the timestamps for this project. 

Project: https://arbimon.org/project/puerto-rico-island-wide/audiodata/recordings

@rassokhina-e Please share your site list in this sheet and I will ask for the list from user as well so that we can double check the we cover all of them.

Site list from user. Check column U to see which sites have been uploaded with version 1.5.10
https://docs.google.com/spreadsheets/d/1vU6CuJVZdt_5DFHo4MtEDAzQOR7jhBSj/edit?usp=sharing&ouid=103265612656038153353&rtpof=true&sd=true

Please update the status of fixing timestamps in the sheet

**Comment by rassokhina-e** [comment]
The site I'm working on now `GUI08`. My plan is to fix this problem, then Noon will review the site, if the timestamps are okay, we will fix all related sites.
