### ISSUE TITLE
The uploader app doesn't open on Windows

### ISSUE THREAD

**Issue by RatreeOchn** [rfcx/ingest-app#230]
Original post: https://rfcx.slack.com/archives/C03FD1WD02J/p1720276866615619
From @carlybatist 

> I've been having an issue where the uploader app doesn't open on Windows. I'm not sure if this is an issue specific to my computer, or if it's perhaps system-wide (It was working great about a week ago).
> I've attached a picture of the message I get when I try to open the application.

![Image](https://github.com/rfcx/arbimon-uploader/assets/51106210/ea49e9aa-b635-4db5-8427-5ec724b3d34e)

**Comment by carlybatist** [comment]
User said he is running Windows 10 Pro on a desktop computer.

**Comment by koonchaya** [comment]
I checked see the same error for the case that user update the app version from the menu. The workaround is uninstalling the app and install the latest version (download from arbimon>import).
